### ISSUE TITLE
Uncaught TypeError

### ISSUE THREAD

**Issue by nkconnor** [steelbrain/autocomplete-hack#11]
1. install Atom hack plugin
2. install AutoComplete hack plugin
3. open new project

**Atom Version**: 0.208.0
**System**: Ubuntu 15.04
**Thrown From**: [autocomplete-hack](https://github.com/steelbrain/autocomplete-hack) package, v1.0.0
### Stack Trace

Uncaught TypeError: Cannot read property 'config' of null

```
At /home/nconnor/.atom/packages/autocomplete-hack/lib/autocomplete-hack.coffee:51

TypeError: Cannot read property 'config' of null
  at Object.Provider.getSuggestions (/home/nconnor/.atom/packages/autocomplete-hack/lib/autocomplete-hack.coffee:51:40)
  at /usr/share/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:255:56
  at Array.forEach (native)
  at AutocompleteManager.module.exports.AutocompleteManager.getSuggestionsFromProviders (/usr/share/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:234:17)
  at AutocompleteManager.getSuggestionsFromProviders (/usr/share/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61)
  at AutocompleteManager.module.exports.AutocompleteManager.findSuggestions (/usr/share/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:221:19)
  at /usr/share/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61

```
### Commands

```
  4x -5:13.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:21.3.0 core:select-all (atom-text-editor.editor.mini.is-focused)
     -1:19.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:58.3.0 application:open (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:03.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
Atom-Hack, v5.0.3
autocomplete-hack, v1.0.0
linter-plus, v0.4.0

# Dev
No dev packages
```

**Comment by nkconnor** [comment]
Issue is resolved by adding the config file from Atom-Hack.

**Comment by steelbrain** [comment]
We should still handle the scenario in the codebase though. and uncaught error doesn't look very nice.

**Comment by steelbrain** [comment]
Fixed in the latest release
