### ISSUE TITLE
Uncaught TypeError: Cannot read property 'config' of null

### ISSUE THREAD

**Issue by luizrodrigomottin** [steelbrain/autocomplete-hack#12]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.0
**System**: Mac OS X 10.10.3
**Thrown From**: [autocomplete-hack](https://github.com/steelbrain/autocomplete-hack) package, v1.0.1
### Stack Trace

Uncaught TypeError: Cannot read property 'config' of null

```
At /Users/mottin/.atom/packages/autocomplete-hack/lib/autocomplete-hack.coffee:51

TypeError: Cannot read property 'config' of null
  at Object.Provider.getSuggestions (/Users/mottin/.atom/packages/autocomplete-hack/lib/autocomplete-hack.coffee:51:40)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:255:56
  at Array.forEach (native)
  at AutocompleteManager.module.exports.AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:234:17)
  at AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61)
  at AutocompleteManager.module.exports.AutocompleteManager.findSuggestions (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:221:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61

```
### Commands

```
     -0:50.3.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:50.3.0 core:cancel (atom-text-editor.editor.is-focused)
  7x -0:48.9.0 core:copy (atom-text-editor.editor.is-focused)
     -0:44.2.0 core:paste (atom-text-editor.editor.is-focused)
     -0:41.7.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:41.7.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:40.8.0 core:save (atom-text-editor.editor.is-focused)
     -0:31 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
  3x -0:26.1.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:25.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
 12x -0:14.2.0 core:copy (atom-text-editor.editor.is-focused)
     -0:04.8.0 core:paste (atom-text-editor.editor.is-focused)
     -0:04.2.0 core:save (atom-text-editor.editor.is-focused)
     -0:03.9.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:03.9.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:01.8.0 core:move-right (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
atom-autocomplete-php, v0.1.4
autocomplete-hack, v1.0.1

# Dev
No dev packages
```

**Comment by steelbrain** [comment]
It's because you haven't installed `Atom-Hack` package.
